apiVersion: v1
data:
  model.conf: |
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, act

    [role_definition]
    g = _, _

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "*")
  policy.csv: |+
    p, admin, /api/v1/*, *

    p, manager, /api/v1/roles, GET
    p, manager, /api/v1/categories, *
    p, manager, /api/v1/categories/*, *
    p, manager, /api/v1/suppliers, *
    p, manager, /api/v1/suppliers/*, *
    p, manager, /api/v1/warehouses, *
    p, manager, /api/v1/warehouses/*, *
    p, manager, /api/v1/products, *
    p, manager, /api/v1/products/*, *
    p, manager, /api/v1/users/change-password, PATCH

    p, operator, /api/v1/categories, GET
    p, operator, /api/v1/categories/:id, GET
    p, operator, /api/v1/suppliers, GET
    p, operator, /api/v1/suppliers/:id, GET
    p, operator, /api/v1/warehouses, GET
    p, operator, /api/v1/warehouses/*, GET
    p, operator, /api/v1/products, GET
    p, operator, /api/v1/products/*, GET
    p, operator, /api/v1/users/change-password, PATCH

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: casbin-config
  namespace: inventory
