apiVersion: v1
kind: Service
metadata:
  name: inventory-redis
  namespace: inventory
  labels:
    app: inventory-redis
spec:
  selector:
    app: inventory-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
